services:
  nginx:
    image: nginx:latest
    container_name: brainwonders-nginx
    ports:
      - "9090:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - brainwonders-net

  php:
    build:
      context: ./docker/php
    container_name: brainwonders-php
    platform: linux/arm64
    volumes:
      - .:/var/www/html
    networks:
      - brainwonders-net

  db:
    image: mysql:5.7
    container_name: brainwonders-mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: brainwonders_db
      MYSQL_USER: bw_user
      MYSQL_PASSWORD: bw_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - brainwonders-net

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: brainwonders-phpmyadmin
    restart: always
    ports:
      - "9091:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: bw_user
      PMA_PASSWORD: bw_pass
    depends_on:
      - db
    networks:
      - brainwonders-net

volumes:
  db_data:

networks:
  brainwonders-net:
    driver: bridge
